### ISSUE TITLE
Not getting the lastest itmes on Mercari JP

### ISSUE THREAD

**Issue by Senachi124** [Kuuuube/marketplace_tracker#1]
It works perfectly fine except it is not getting the lastest items on the mercari.jp.
i.e. the first page item cannot be scrap, but all the items in second page can be scrap properly

the URL looks like : "https://jp.mercari.com/search?keyword=(the_keyword)&order=desc&sort=created_time"

Anyways to fix it or it is the API issue?

**Comment by Kuuuube** [comment]
Good catch! There was an api change that I didn't notice. Should be fixed with [54379cb](https://github.com/Kuuuube/marketplace_tracker/commit/54379cbfbea5f3bb5081095b53015ee6eeac5982).
